Update imap4.py to fix a minor bug
The sendNegativeResponse method requires all parameters to be in byte[] instead of string. It'll thow an exception like this:
```
     File ".venv/lib/python3.12/site-packages/twisted/mail/imap4.py", line 1101, in _respond
            self.sendLine(b" ".join((tag, state, message)))
        builtins.TypeError: sequence item 2: expected a bytes-like object, str found
```